### ISSUE TITLE
Support Angular 2.0.0-rc.1

### ISSUE THREAD

**Issue by pwasilewski** [rosslavery/angular2-tag-input#1]
Dear rosslavery,

Can you please upgrade your module to support Angular 2.0.0-rc.1?

Thank you for your help! :)

**Comment by rosslavery** [comment]
Hey,

Will try to get to this as soon as I can. Pretty busy at the moment though.

PR welcome, otherwise I'll get to it ASAP!

**Comment by mark-langer** [comment]
Hey guys, I got the plugin ready for angular2-rc.1

As soon as @rosslavery merges the new commit, you should be all set, @pwasilewski !

**Comment by ducduongtmb** [comment]
Hi @mark-langer
How can I map this Module in System config file ?
Thanks you .

**Comment by mark-langer** [comment]
Hi ducduongtmb,

You don't have to. You're all set as soon as you reference the component in your own components. Check the Quickstart section or the plnkr on the code page of this repo to see that in action.
