### ISSUE TITLE
Add metadata.json file generation for Angular AoT compilation support

### ISSUE THREAD

**Issue by goatcube** [rosslavery/angular2-tag-input#15]
I'm using this control in an Angular 2 project and I have issues when attempting to compile ahead of time. Can you add a metadata.json file to support ahead of time compilation?

**Comment by ayydevara** [comment]
I have the same problem, can you please take care of this issue ASAP

Thanks.

**Comment by rosslavery** [comment]
I will be adding AoT compatibility in a new release today or tomorrow.

**Comment by rosslavery** [comment]
Should be added in latest release.
