### ISSUE TITLE
 Property 'delimiter' does not exist error

### ISSUE THREAD

**Issue by karthikkavin** [rosslavery/angular2-tag-input#3]
tag-input.component.ts (112, 57): Property 'delimiter' does not exist on type 'TagInputComponent' on _splitString() function.

**Comment by shaibansid** [comment]
+1

**Comment by rosslavery** [comment]
Hi all,

Sorry for not being more responsive -- very busy at work and haven't had time to work on OSS projects.

I've just published a new version (with breaking changes, see changelog) that fixes this issue by virtue of some of the changes I made.
