### ISSUE TITLE
Can't bind to 'ngModel' 

### ISSUE THREAD

**Issue by YouNesta** [rosslavery/angular2-tag-input#7]
Can't bind to 'ngModel' since it isn't a known property of 'rl-tag-input'.
I'm at the latest Angular-CLI version

thanks for all

**Comment by rosslavery** [comment]
Did you manage to figure this out?

**Comment by YouNesta** [comment]
Yes thanks, i need to import the FormsModule package in your Angular module before using two way data binding ;)
